print("Reglas del juego UNO")
print("1. El objetivo es ser el primer jugador en quedarse sin cartas.")
print("2. Cada jugador comienza con 7 cartas.")
print("3. Se juega por turnos en sentido horario.")
print("4. En tu turno debes lanzar una carta que coincida en color o número con la carta del centro.")
print("5. Si no puedes jugar una carta, debes robar una del mazo.")
print("6. Hay cartas especiales: +2, reversa, salto de turno, comodín y comodín +4.")
print("7. Cuando te queda una sola carta, debes decir 'UNO'. Si no lo haces y otro jugador se da cuenta, robas 2 cartas.")
print("8. Gana el primer jugador que se queda sin cartas.")