print("Tutorial: Cómo lavar los platos correctamente")
print("")
print("1. Reunir todos los materiales necesarios:")
print("   - Esponja suave para platos delicados y un estropajo para platos con grasa o suciedad pesada.")
print("   - Detergente líquido para lavar platos.")
print("   - Agua caliente.")
print("")
print("2. Prepara el área de lavado:")
print("   - Limpiar el fregadero .")
print("   - Llenar el fregadero con agua caliente o un pequeño bañador y añade una cantidad adecuada de detergente.")
print("3. Orden para lavar los platos:")
print("   a) Comenzar con los vasos y tazas, que suelen estar menos sucios.")
print("   b) Luego, lavar los cubiertos.")
print("   c) Después, lavar los platos y bowls.")
print("   d) Finalmente, lavar ollas y sartenes, que suelen tener grasa o comida quemada.")
print("")
print("4. Enjuagar cada plato con bastante agua para eliminar todo el detergente y residuos.")
print("")
print("5. Secado:")
print("   - Colocar los platos en un escurridor para que se sequen al aire.")
print("   - Si deseas, seca con una toalla limpia para evitar manchas de agua.")
print("   - Asegurarse que todos los platos estén bien secos antes de guardarlos.")
print("")
print("5. Limpieza final:")
print("   - Vacíar el fregadero, limpia la esponja y el área de trabajo.")
print("   - Dejar secar la esponja en un lugar ventilado para evitar bacterias.")
print("")
print("¡Listo!.")
